### ISSUE TITLE
Move "description" field in YAML

### ISSUE THREAD

**Issue by waldoj** [openva/crump#50]
The present order of fields is confusing:

``` yaml
- name:        table-identifier
  type:        A
  start:       2
  length:      2
  description: ID for Specific Table
- name:        table-code
  type:        A
  start:       4
  length:      10
  description: Table code
- name:        table-desc
  type:        A
  start:       14
  length:      50
  description: Value for Table Code
```

Putting `name` first and `description` last makes it logical for a reader to group together descriptions and the following name, even though they're unrelated. Move the `description` field up to appear after `name` to prevent this confusion.
