### ISSUE TITLE
Mappings with geodata can't be generated from YAML

### ISSUE THREAD

**Issue by waldoj** [openva/crump#82]
Our JSON mapping geodata needs to look like this:

``` json
"location": {
    "type": "object",
    "properties": {
        "coordinates": {
            "type": "geo_point",
            "lat_lon": "true"
        }
    }
}
```

All we have right now in our YAML is this:

``` yaml
- name:        corp-coordinates
  alt_name:    coordinates
  description: Latitude and longitude of Principal address
  group:       address
  search:
    type:      geo_point
```

Somehow we have to figure out how to use that YAML to generate that JSON. Until that happens, our geosearch functionality is going to break every week, when the data is updated.
